name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            # Stop and remove existing container
            docker stop boston-app || true
            docker rm boston-app || true

            # Remove old image
            docker rmi bostonhousepricing_end_to_end || true

            # Clone latest repo
            rm -rf BostonHousePricing_End_to_End
            git clone https://github.com/${{ github.repository }}.git
            cd BostonHousePricing_End_to_End

            # Build and run Docker container
            docker build -t bostonhousepricing_end_to_end .
            docker run -d -p 5000:5000 --name boston-app bostonhousepricing_end_to_end
          EOF
